package pt.up.fe.lpoo.towerdefense;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * This class handles the game's string bundles. Partially automatically generated by Eclipse.
 * @author Joao Marinheiro
 * @author Luis Cleto
 */
public class Messages {
	private static final String BUNDLE_NAME = "pt.up.fe.lpoo.towerdefense.messages"; //$NON-NLS-1$
	private static final String BUNDLEPT_NAME = "pt.up.fe.lpoo.towerdefense.messagesPT";
	private static final String BUNDLEPIRATE_NAME = "pt.up.fe.lpoo.towerdefense.messagesPIRATE";

	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle
			.getBundle(BUNDLE_NAME);
	private static final ResourceBundle RESOURCEPT_BUNDLE = ResourceBundle
			.getBundle(BUNDLEPT_NAME);
	private static final ResourceBundle RESOURCEPIRATE_BUNDLE = ResourceBundle
			.getBundle(BUNDLEPIRATE_NAME);
	
	/** Indicator for using the english strings */
	public static final int LANG_EN = 0;
	/** Indicator for using the portuguese strings */
	public static final int LANG_PT = 1;
	/** Indicator for using the pirate speak strings */
	public static final int LANG_PIRATE = 2;
	
	private static final ResourceBundle langBundles[] = {RESOURCE_BUNDLE, RESOURCEPT_BUNDLE, RESOURCEPIRATE_BUNDLE};
	private static int langInUse = LANG_EN;
	private Messages() {
	}

	/**
	 * Retrieves a given string from the resource bundle currently in use
	 * @param key key matching the desired string
	 * @return returns the string if found, string with the key value between '!' otherwise
	 */
	public static String getString(String key) {
		try {
			return langBundles[langInUse].getString(key);
		} catch (MissingResourceException e) {
			return '!' + key + '!';
		}
	}
	
	/**
	 * Indicates which language is currently being used
	 * @return returns an int corresponding to one of the language indicators
	 */
	public static int getCurrentLang(){
		return langInUse;
	}
	
	/**
	 * Changes the language being used if the indicated language is valid
	 * @param newLang indicator of the new language to use
	 */
	public static void setLang(int newLang){
		if(newLang >= 0 && newLang <= LANG_PIRATE)
			langInUse = newLang;
	}
}
